"use client";

import Link from "next/link";
import { BarChart3, Bell, CheckCircle2, ChevronRight, Clock3, History, Home, LogOut, TableProperties, WalletCards } from "lucide-react";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Brand } from "@/components/shared/brand";
import { formatInr } from "@/lib/currency";

export function EmployeeDashboard() {
  return (
    <div className="min-h-screen bg-[#f5f1e8] pb-24">
      <header className="border-b border-[#dfd8cb] bg-[#173a34] text-white"><div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-4 sm:px-6"><Brand inverse /><div className="flex items-center gap-2"><Button variant="ghost" size="icon" className="text-white/70 hover:bg-white/10 hover:text-white" aria-label="Notifications"><Bell className="size-4" /></Button><Avatar className="size-8"><AvatarFallback className="bg-[#f5c95f] text-xs font-semibold text-[#173a34]">AM</AvatarFallback></Avatar></div></div></header>
      <main className="mx-auto max-w-5xl space-y-5 px-4 py-6 sm:px-6">
        <section className="flex items-end justify-between gap-4"><div><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-emerald-600" /><p className="text-xs font-semibold tracking-wider text-primary uppercase">Dinner shift · Live</p></div><h1 className="mt-2 text-2xl font-semibold tracking-[-0.04em]">Namaste, Arjun</h1><p className="mt-1 text-sm text-muted-foreground">You’re serving Tables 3 and 6.</p></div><Button variant="ghost" size="icon" asChild><Link href="/"><LogOut className="size-4" /></Link></Button></section>
        <Card className="overflow-hidden border-0 bg-[#173a34] py-0 text-white shadow-[0_20px_60px_rgba(22,57,50,0.18)]"><CardContent className="relative p-6 sm:p-8"><div className="absolute -end-16 -top-20 size-52 rounded-full bg-[#f5c95f]/12 blur-2xl" /><p className="relative text-xs text-white/55">Your tips this shift</p><p className="font-tabular relative mt-2 text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">{formatInr(184_000)}</p><p className="relative mt-2 flex items-center gap-1.5 text-xs text-[#9dc8b9]"><CheckCircle2 className="size-3.5" /> All 8 allocations are balanced</p><div className="relative mt-6 grid grid-cols-3 divide-x divide-white/10 rounded-2xl bg-white/5 py-3"><div className="px-3"><p className="text-[10px] text-white/45">Direct</p><p className="font-tabular mt-1 text-sm font-semibold">₹1,288</p></div><div className="px-3"><p className="text-[10px] text-white/45">Pool</p><p className="font-tabular mt-1 text-sm font-semibold">₹552</p></div><div className="px-3"><p className="text-[10px] text-white/45">Pending</p><p className="font-tabular mt-1 text-sm font-semibold">₹0</p></div></div></CardContent></Card>
        <section className="grid gap-3 sm:grid-cols-2">
          {[{ number: 3, status: "Bill ready", guests: 4, bill: "₹2,450", lastTip: "Awaiting tip" }, { number: 6, status: "Tip received", guests: 4, bill: "₹2,000", lastTip: "+₹140 to you" }].map((table) => <Card key={table.number} className="gap-3 border-[#ded7ca] bg-white/75 py-4 shadow-none"><CardContent className="px-4"><div className="flex items-start justify-between"><div><p className="text-[10px] font-medium text-muted-foreground uppercase">Assigned table</p><p className="font-tabular mt-1 text-2xl font-semibold">{table.number}</p></div><Badge variant="outline" className={table.status === "Tip received" ? "border-[#c8dfd4] bg-[#e5f0ea] text-[#2e735f]" : "border-[#e8d2aa] bg-[#f7ecd5] text-[#966b20]"}>{table.status}</Badge></div><div className="mt-4 flex items-end justify-between"><div><p className="text-xs text-muted-foreground">{table.guests} guests · {table.bill}</p><p className="mt-1 text-xs font-semibold text-primary">{table.lastTip}</p></div><ChevronRight className="size-4 text-muted-foreground" /></div></CardContent></Card>)}
        </section>
        <Card className="gap-0 border-[#ded7ca] bg-white/75 py-0 shadow-none"><CardHeader className="flex-row items-center justify-between border-b border-[#e8e1d6] px-5 py-4"><CardTitle className="text-sm">Recent allocations</CardTitle><Button variant="ghost" size="sm" className="text-xs">View all <ChevronRight className="size-3.5" /></Button></CardHeader><CardContent className="divide-y divide-[#ebe5db] px-5">{[{ table: 6, time: "9:42 PM", source: "POS import", amount: 14_000 }, { table: 1, time: "9:18 PM", source: "Digital", amount: 12_600 }, { table: 8, time: "8:54 PM", source: "Cash", amount: 8_750 }].map((tip) => <div key={`${tip.table}-${tip.time}`} className="flex items-center gap-3 py-3.5"><span className="flex size-9 items-center justify-center rounded-xl bg-[#e5eee9] text-primary"><WalletCards className="size-4" /></span><div className="flex-1"><p className="text-xs font-semibold">Table {tip.table} <span className="font-normal text-muted-foreground">· {tip.time}</span></p><p className="mt-1 text-[10px] text-muted-foreground">{tip.source} · 70% share</p></div><strong className="font-tabular text-sm">+{formatInr(tip.amount)}</strong></div>)}</CardContent></Card>
        <Card className="gap-3 border-[#ded7ca] bg-[#f7ecd5] py-4 shadow-none"><CardContent className="flex items-center gap-3 px-4"><Clock3 className="size-5 text-[#966b20]" /><div className="flex-1"><p className="text-xs font-semibold">Payout after shift approval</p><p className="mt-1 text-[11px] text-muted-foreground">Your manager will finalize the amount when the shift closes.</p></div><strong className="font-tabular text-sm">₹1,840</strong></CardContent></Card>
      </main>
      <nav className="fixed inset-x-3 bottom-3 mx-auto grid max-w-md grid-cols-4 rounded-2xl border border-white/10 bg-[#173a34]/96 p-1.5 text-white shadow-xl backdrop-blur"><a href="#" className="flex min-h-12 flex-col items-center justify-center gap-1 rounded-xl bg-white/10 text-[10px]"><Home className="size-[18px] text-[#f5c95f]" /> Home</a><a href="#tables" className="flex min-h-12 flex-col items-center justify-center gap-1 text-[10px] text-white/50"><TableProperties className="size-[18px]" /> Tables</a><a href="#earnings" className="flex min-h-12 flex-col items-center justify-center gap-1 text-[10px] text-white/50"><BarChart3 className="size-[18px]" /> Earnings</a><a href="#history" className="flex min-h-12 flex-col items-center justify-center gap-1 text-[10px] text-white/50"><History className="size-[18px]" /> History</a></nav>
    </div>
  );
}
